apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: us-east1-docker.pkg.dev/csci-5409-417319/container-images/app2:latest
          ports:
            - containerPort: 6001
          volumeMounts:
            - name: shared-volume
              mountPath: /mohammed_PV_dir
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 81
      targetPort: 6001
  selector:
    app: app2
